/* ============================================================
   generator.js — Generates a new philosopher node + its
   connections to existing philosophers.

   RIGHT NOW THIS IS A STUB: it returns plausible canned data so
   the whole add-philosopher UX can be built and tested without a
   backend or API key. The real Claude call is written out in
   comments at the LLM INTEGRATION POINT below — swapping it in is
   a localized change because `generate()` is already async.
   ============================================================ */

const Generator = (() => {
  // Schools we are allowed to assign (must match the CSS palette
  // and graph lane order). The real model output must be constrained
  // to this list too.
  const SCHOOLS = [
    "presocratic", "classical", "hellenistic", "late-antique", "medieval",
    "renaissance", "rationalism", "empiricism", "enlightenment", "german-idealism",
    "19c-continental", "utilitarianism", "pragmatism", "phenomenology-existentialism",
    "analytic", "critical-theory", "hermeneutics", "poststructuralism",
    "political", "feminist", "philosophy-of-science",
  ];

  const RELATION_TYPES = [
    "continuacion", "critica", "reinterpretacion",
    "radicalizacion", "inversion", "diagnostico",
  ];

  function slugify(name) {
    return name.toLowerCase().normalize("NFD").replace(/\p{M}/gu, "")
      .replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
  }

  // ---------------------------------------------------------------------
  // STUB IMPLEMENTATION
  // Produces a believable-looking node and a couple of proposed links to
  // real existing philosophers, so the preview/confirm flow is exercised.
  // ---------------------------------------------------------------------
  function stubGenerate(name, ctx) {
    const roster = ctx.philosophers || [];
    // Pick a school: bias toward a modern one so the node lands in a
    // populated lane; deterministic-ish by name length for variety.
    const school = SCHOOLS[name.length % SCHOOLS.length];

    // Choose up to 3 distinct existing philosophers to connect to,
    // preferring ones in the same school, then anyone.
    const sameSchool = roster.filter((p) => p.school === school);
    const pool = (sameSchool.length >= 3 ? sameSchool : roster).slice();
    const picks = [];
    for (let i = 0; i < pool.length && picks.length < 3; i++) {
      const idx = (name.length * 7 + i * 13) % pool.length;
      if (!picks.includes(pool[idx])) picks.push(pool[idx]);
    }

    const id = slugify(name);
    const philosopher = {
      id,
      name,
      dates: "20th c. (generated)",
      school,
      tradition: "Generated entry — edit me",
      region: "Unknown",
      central_ideas: [
        "Placeholder idea — replace with real content",
        "This node was generated by the stub generator",
      ],
      key_works: ["(works unknown — generated entry)"],
      short_description:
        `A generated placeholder entry for ${name}. Connect a real language model ` +
        `at the LLM integration point in generator.js to produce genuine biography, ` +
        `ideas, works, and connections.`,
      generated: true,
    };

    const relations = picks.map((target, i) => {
      const type = RELATION_TYPES[(name.length + i) % RELATION_TYPES.length];
      return {
        id: `${id}-${target.id}`,
        source: id,
        target: target.id,
        type,
        bridge: "Generated connection",
        title: `${name} and ${target.name}`,
        summary:
          `A proposed (generated) connection between ${name} and ${target.name}. ` +
          `Replace with a real reading of how they relate.`,
        generated: true,
      };
    });

    return { philosopher, relations };
  }

  // ---------------------------------------------------------------------
  // PUBLIC API
  // `generate(name, ctx)` resolves to { philosopher, relations }.
  // ctx = { philosophers: [...] } — the current roster, so connections
  // can target real nodes.
  // ---------------------------------------------------------------------
  async function generate(name, ctx) {
    ctx = ctx || {};

    // Simulate latency so the spinner/preview UX is realistic.
    await new Promise((r) => setTimeout(r, 650));

    /* === LLM INTEGRATION POINT ===========================================
       Replace the stubGenerate(...) call below with a real Claude request.
       Recommended wiring (use the `claude-api` skill when implementing):

       - Model: "claude-sonnet-4-6" (fast/cheap, good enough). Use
         "claude-opus-4-8" for the highest-quality biographies.
       - Use tool-use / structured output so the model returns JSON that
         already matches our schema (philosopher + relations[]).
       - Put the EXISTING ROSTER in a cached system block so the model only
         connects to real nodes and so repeat calls are cheap:

         const roster = (ctx.philosophers || [])
           .map(p => `${p.id}\t${p.name}\t${p.school}`).join("\n");

         const res = await fetch(API_URL, {            // API_URL = your
           method: "POST",                              // serverless proxy,
           headers: {                                   // or the Anthropic
             "content-type": "application/json",        // endpoint with a
             // For BYOK direct-from-browser calls you also need:
             //   "x-api-key": userKey,
             //   "anthropic-version": "2023-06-01",
             //   "anthropic-dangerous-direct-browser-access": "true",
           },
           body: JSON.stringify({
             model: "claude-sonnet-4-6",
             max_tokens: 1500,
             system: [
               { type: "text",
                 text: "You add philosophers to a graph of Western philosophy. "
                     + "Return one philosopher object and 1–4 relations to "
                     + "EXISTING philosophers only. school must be one of: "
                     + SCHOOLS.join(", ") + ". relation type one of: "
                     + RELATION_TYPES.join(", ") + ". Arrows point from the "
                     + "later thinker to the earlier one." },
               { type: "text", text: "ROSTER (id\\tname\\tschool):\n" + roster,
                 cache_control: { type: "ephemeral" } },   // cache the roster
             ],
             tools: [ADD_PHILOSOPHER_TOOL],   // JSON schema = our data model
             tool_choice: { type: "tool", name: "add_philosopher" },
             messages: [{ role: "user",
               content: `Add the philosopher: ${name}` }],
           }),
         });
         const data = await res.json();
         const out = data.content.find(c => c.type === "tool_use").input;
         return { philosopher: out.philosopher, relations: out.relations };

       Until then, the stub keeps everything working:
       ===================================================================== */
    return stubGenerate(name, ctx);
  }

  return { generate, slugify, SCHOOLS, RELATION_TYPES };
})();
